# Generated by Django 4.0.3 on 2022-03-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('remarks', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('remarks', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='ExpensesTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('remarks', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('remarks', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('date', models.DateField()),
                ('remarks', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('gender', models.CharField(max_length=1)),
                ('father_name', models.CharField(max_length=256)),
                ('caste', models.CharField(max_length=256)),
                ('cnic', models.CharField(max_length=256)),
                ('dob', models.DateField()),
                ('qualification', models.CharField(max_length=256)),
                ('date_of_first_appointment', models.DateField()),
                ('contact', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=1024)),
                ('remarks', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='UploadStaffDocsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_tile', models.CharField(max_length=256)),
                ('document', models.FileField(upload_to='uploads/')),
                ('remarks', models.CharField(max_length=1024)),
            ],
        ),
    ]
