# Generated by Django 4.0.3 on 2022-03-02 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_designationmodel_expenses_expensestypes_rolemodel_and_more'),
        ('user', '0002_alter_customuser_staff_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.AddField(
            model_name='uploadstaffdocsmodel',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.staffmodel'),
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='designation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.designationmodel'),
        ),
        migrations.AddField(
            model_name='salarymodel',
            name='designation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.designationmodel'),
        ),
        migrations.AddField(
            model_name='salarymodel',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.staffmodel'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='expenses_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.expensestypes'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.staffmodel'),
        ),
    ]
